export const cards = [
  {
    id: 1,
    title: "Plumber",
    desc: "Add talent to AI",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiukn2xhjcFKLi5s8ji9f2_yrNdKWlq2MVU7R-N0hSlpL2Xp21dy9iAecv3DDZSZVADMAb6b-KXcPz-HkHPX1eAvBoYJV8YFDi6HsEC8lvNbgTCMYOU7Qvl2-R9jb_EgvSjL7XbYiLskb7mw_a47Sgu0At5L3KCyA1oN6CpIE1yrmSDQCpbzoa2K2XsR3Qs/s329/Plumber.png",
  },
  {
    id: 2,
    title: "Painter",
<<<<<<< HEAD
    desc: "Build your brand",
=======
    desc: "Build yor brand",
>>>>>>> 24a3dd31caa041428bf7f4a22f2cd4289ef2caaa
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhJpoIwwCuyJhbK4z2mTO8Jjd41aWpQ7fHRQXJlxByE7mKLF8EZ9WiqAFHqnhkpmGb6Rxn8CSP1idZ8yy-8kXSMbzkRESbM7NYY0IoXEjmh2i-43dQbEMOHhP_OPachvkNOBHS_gu87AxOwT_Rc-bSsaTlfBDy8hR3o8gXfsME-4QfltMcK7L9ZzlPTBMz2/s329/Painter.png",
  },
  {
    id: 3,
    title: "Roofer",
    desc: "Customize your site",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhA3JSN1tNKBYzIJtyRP31AAJg9pu_14X806ds7G6ZVuPO9TDd4tPVejkN30BrZpdX8dHzipM2rITqcMADB0eOhtwtWHbG3s95BbQWwn1ViSYvKSEMP9G6QJctmf-waZOAE3rXXaUgfmCWbFCLuvOsi973yVTSU4wMGfNpdsUxKDVYxIgtSL58760nOqCDy/s329/Roofer.png",
  },
  {
    id: 4,
    title: "Tiller",
    desc: "Share your message",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEghRz7pNYIsDwYCNV4HEMea7l7qcQtoBptDFDheKuC6B0W1iExsjQ8I9AqyOqu1bePT_eX0CxNaD4vtZ88Wd3e8J4qnB8jhC6Lxkb4A-BG4Ux5UdvBrnJSGReQrZJ3xIZsrRuyjH899Pem9jl_v5Egz4xjhEo92VP6xsfVRBKjjSyZ9oIKzz-qcBX3aJycy/s329/Tile.png",
  },
  {
    id: 5,
    title: "Mason",
    desc: "Engage your audience",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxZgEkAzpFh3WxSVfkvMTsEKSegjqkQLBBerrc4fc7giqw6xQMeUBQukA8Tr3TzbG2s3CcZqFv1xKoIAWMMoySAcuPp_vIZIIB7U2SrNt6ZjUPBDIQT61paiDc-KY_bIv8zZMP1xPcKhU_NW_cu64uc11MmBYByOPqD6bhTxm9yVQ-BNnzVt7rflL3pHF7/s320/Mason.png",
  },
  {
    id: 6,
    title: "Helper",
    desc: "Reach more customers",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhUG6ss0JJoXuJ9hyphenhyphenLey8sQZWMRnMPlIUrMHdhCGtsiOeDy3BBahla-6bwiCf7Aqd127fAau6A9nM7k4KvoAKW4R9_T0sFZYEmLeMHHYVj6FZRvIhP7wJM3vfTnW087qaFcrZjLZqWtNBh83cN6Vwyk4_onIVjGpx17LMepUEPuifht-HmScDA3EkICcKOW/s329/Helper.png",
  },
  {
    id: 7,
    title: "Electrician",
    desc: "Unlock growth online",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhr81ZgV2hQSGbJ6mQAjpw0T3u6nPVmOo7H3k2vwqzghwfyU9j_SSjWwhpE6glG-s5p_Nek-yhgQog-g-8LTRI_tEIqbcozoKS5_SBPhiJBviQRmFIUS2TUFeSjuMBOBUJLAcdF6aTmxdBCngO5-rXckaIPYnuHc2i9qre5PSw1r1BJmQ2Q30zhT8VD3wsE/s329/Electrician.png",
  },
  {
    id: 8,
    title: "Aluminiumn",
    desc: "Color you dreams",
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgXFDfX4plfgPkI0ilka9sOREDAuiu9RFjBqx_DXPn6zt-S587mgVJyZ0DrwG4vPJAnUrwkFwiPHVdx8Eg9ld_hi8NaZJtUe8SnV1O-h0UIpwHdpqOVLmDz2TLkRZN3KBn9ejO0FTEeZcvrc9BMwthdOoEjwjFLgauFCE-sx9-yfn4Xnzv9z_qdNMI7ubZX/s329/Aluminium.png",
  },
];

  export const projects = [
    {
      id: 1,
      img: "https://www.housedigest.com/img/gallery/should-you-paint-your-walls-and-ceilings-the-same-color/intro-1672764805.jpg",
      pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Painting",
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://angelmanagementsolutions.com/wp-content/uploads/2023/03/q1.jpg",
      pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Plumbing",
      username: "Morton Green",
    },
    {
      id: 3,
      img: "https://onepullwire.com/wp-content/uploads/2022/02/10-Specializations-Comm-Electricians.jpeg",
      pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Electrical",
      username: "Emmett Potter",
    },
    {
      id: 4,
      img: "https://www.workbc.ca/sites/default/files/styles/hero_image/public/NTI5NzE_5JlNHrHAUkbq57B2-7611-NOC.jpg?itok=lq9_wNOz",
      pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Helping",
      username: "Freddie Johnston",
    },
    {
      id: 5,
      img: "https://www.shutterstock.com/image-photo/carpenter-working-equipment-on-wooden-600nw-1886769229.jpg",
      pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Carpenting",
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://tonytiling.ie/wp-content/uploads/2023/12/Achieve-Flawless-Floors-The-Secrets-of-Tile-Leveling-Systems-Unveiled.jpg",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Tilling",
      username: "Dalton Hudson",
    },
    {
      id: 7,
      img: "https://i0.wp.com/www.jbcroofcover.co.za/wp-content/uploads/2023/11/jbc-roof-cover-roofing-company.webp?fit=1024%2C678&ssl=1",
      pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Roofing",
      username: "Hannah Dougherty",
    },
    {
      id: 8,
      img: "https://servicewiseelectrical.com/wp-content/uploads/New-electrical-wiring-installation.jpg",
      pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
      cat: "Wiring and Wood",
      username: "Ward Brewer",
    },
  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://powerpillar.co.uk/wp-content/uploads/2022/10/Untitled-design-47.png",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will Paint your construction based on your images and prompts",
      price: 59,
      star: 5,
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://www.solarrun.com.au/wp-content/uploads/2022/03/shutterstock_1696454704.jpg",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide all electrical works related to your plan",
      price: 79,
      star: 5,
      username: "Lannie Coleman",
    },
    {
      id: 3,
      img: "https://www.strongguard.com.au/wp-content/uploads/2021/03/gradual-roof-pitch.jpg",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide my service related to roofing",
      price: 112,
      star: 5,
      username: "Carol Steve",
    },
    {
      id: 4,
      img: "https://www.home-designing.com/wp-content/uploads/2009/04/all-purpose-ceramic-tiles-forum.jpg",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide all tilling solution with latest desings",
      price: 99,
      star: 4,
      username: "Don Weber",
    },
    {
      id: 5,
      img: "https://4.imimg.com/data4/BC/II/MY-26982184/wooden-work-500x500.jpg",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide wood based services to your plan",
      price: 59,
      star: 5,
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://t3.ftcdn.net/jpg/08/66/52/24/360_F_866522497_yRP4o1ASMrFSsKimGsVMWenmHPlVcuw1.jpg",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will provide all types of wiring works",
      price: 79,
      star: 4,
      username: "Walton Shepard ",
    },
    {
      id: 7,
      img: "https://chamblissplumbing.com/wp-content/webp-express/webp-images/uploads/2023/03/whats-a-plumber-1.jpg.webp",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate plumbing works for your construction",
      price: 89,
      star: 5,
      username: "Waverly Schaefer",
    },
    {
      id: 8,
      img: "https://www.laborfinders.com/media/durfrltj/construction.jpg?quality=80",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom services for your plan",
      price: 110,
      star: 4,
      username: "Wilton Hunt",
    },
  ];
  